# Generated by Django 4.1.2 on 2023-06-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tipo_mueble', models.IntegerField(choices=[[0, 'Escritorio'], [1, 'Buffert'], [2, 'Mesa'], [3, 'Rack'], [4, 'Velador'], [5, 'Closet']])),
                ('precio', models.IntegerField()),
                ('tipo_madera', models.CharField(max_length=50)),
                ('nuevo', models.BooleanField()),
                ('fecha_fabricacion', models.DateField()),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MueblesM.descripcion')),
            ],
        ),
    ]
